[colors]
draw_bold_text_with_bright_colors = true

#
[font]
size = 13

[font.normal]
family = "CaskaydiaCove Nerd Font"

[window]
opacity = 0.9

[general]
import = [
	"~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]
